var burgundy = {
        '.column':{'fill':'#fff','stroke':'#fff'},
        '.backGround':{'fill':'#76273f'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#fff','font-weight':'100'},
        '.annotation':{'fill':'#fff','font-weight':'400'},
        '.source':{'fill':'#fff','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#fff','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#fff','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none','stroke':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.refLine text':{'fill':'#fff','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#fff','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.highLight':{'stroke':'#fff','stroke-width':'5px','fill':'none'}
    };

var grey = {
        '.column':{'fill':'#c89a2c','stroke':'#c89a2c'},
        '.backGround':{'fill':'#343334'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#fff','font-weight':'100'},
        '.annotation':{'fill':'#c89a2c','font-weight':'400'},
        '.source':{'fill':'#fff','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#c89a2c','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#fff','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none','stroke':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.refLine text':{'fill':'#fff','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#fff','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.highLight':{'stroke':'#c89a2c','stroke-width':'5px','fill':'none'}
    };

var skyblue = {
        '.column':{'fill':'#004a6c','stroke':'#004a6c'},
        '.backGround':{'fill':'#d3e2ea'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#000','font-weight':'100'},
        '.annotation':{'fill':'#004a6c','font-weight':'400',},
        '.source':{'fill':'#000','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#004a6c','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#000','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none','stroke':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#000','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#000','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.refLine text':{'fill':'#000','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#000','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.highLight':{'stroke':'#004a6c','stroke-width':'5px','fill':'none'}
    };

var palegreen = {
        '.column':{'fill':'#343334','stroke':'#343334'},
        '.backGround':{'fill':'#b9c8b8'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#000','font-weight':'100'},
        '.annotation':{'fill':'#343334','font-weight':'400'},
        '.source':{'fill':'#000','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#343334','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#000','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none','stroke':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#000','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#000','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.refLine text':{'fill':'#000','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#000','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.highLight':{'stroke':'#343334','stroke-width':'5px','fill':'none'}
    };

var duckegg = {
        '.column':{'fill':'#fff','stroke':'#fff'},
        '.backGround':{'fill':'#80a9ac'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#000','font-weight':'100'},
        '.annotation':{'fill':'#fff','font-weight':'400'},
        '.source':{'fill':'#000','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#fff','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#000','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none','stroke':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#000','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#000','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.refLine text':{'fill':'#000','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#000','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#000','stroke-width':'1px'},
        '.highLight':{'stroke':'#fff','stroke-width':'5px','fill':'none'}
    };

var deepblue = {
        '.column':{'fill':'#fff','stroke':'#fff'},
        '.backGround':{'fill':'#385a94'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#fff','font-weight':'100'},
        '.annotation':{'fill':'#fff','font-weight':'400'},
        '.source':{'fill':'#fff','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#fff','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#fff','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.refLine text':{'fill':'#fff','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#fff','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.highLight':{'stroke':'#fff','stroke-width':'5px','fill':'none'}
    };

var greenblue = {
        '.column':{'fill':'#fff','stroke':'#fff'},
        '.backGround':{'fill':'#80a9ac'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#ffffff','font-weight':'100'},
        '.annotation':{'fill':'#ffffff','font-weight':'400',},
        '.source':{'fill':'#ffffff','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#ffffff','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
       '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#fff','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#fff','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.refLine text':{'fill':'#000','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#000','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#fff','stroke-width':'1px'},
        '.highLight':{'stroke':'#ffffff','stroke-width':'5px','fill':'none'}
    };


var ftpink = {
        '.column':{'fill':'#8c3c57','stroke':'#8c3c57'},
        '.backGround':{'fill':'#fff1e0'},
        'text':{'font-family':'Metric, sans-serif'},
        '.title':{'fill':'#202222','font-weight':'100'},
        '.annotation':{'fill':'#8c3c57','font-weight':'400'},
        '.source':{'fill':'#4c4c48','font-size':'16px','font-weight':'100'},
        '.primary_line':{'fill':'none','stroke':'#8c3c57','stroke-width':'5px','stroke-linecap':'round','stroke-linejoin':'round'},
        '.secondary_line':{'display':'none'},
        '.xAxis path':{'fill':'none'},
        '.xAxis text':{'fill':'#4c4c48','font-weight':'100','text-anchor':'middle'},
        '.xAxis line':{'fill':'none','stroke':'none'},
        '.xAxisTime path':{'fill':'none'},
        '.xAxisTime text':{'fill':'#4c4c48','font-weight':'100','font-size':'26px','text-anchor':'middle'},
        '.xAxisTime line':{'fill':'none','stroke':'#4c4c48','stroke-width':'1px'},
        '.yAxis path':{'fill':'none'},
        '.yAxis text':{'fill':'#4c4c48','font-weight':'100','font-size':'26px','text-anchor':'end'},
        '.yAxis line':{'fill':'none','stroke':'#b2a695','stroke-width':'1px'},
        '.refLine text':{'fill':'#4c4c48','font-weight':'100','font-size':'22px','text-anchor':'start'},
        '.refLine line':{'fill':'none','stroke':'#4c4c48','stroke-width':'1px','stroke-dasharray':'2,2'},
        '.zeroLine':{'fill':'none','stroke':'#4c4c48','stroke-width':'1px'},
        '.highLight':{'stroke':'#8c3c57','stroke-width':'5px','fill':'none'}
    };
